stages:
  - build

build-licensight-file:
  stage: build
  script:
    - echo "install licensight-file"
    - curl -O https://licensight-v2.s3.eu-central-1.amazonaws.com/latest/linux/licensight-file
    - chmod +x ./licensight-file
    - echo "repository name is $CI_PROJECT_NAME"
    - echo "push SBOM to licensight"
    - ./licensight-file generate ./ -a $PROJECT_NAME -p demo -e $ENV -t $SECRET_KEY
  rules:
    - if: '$CI_PIPELINE_SOURCE == "aaaaaa"'




build-licensight-scan:
  stage: build
  script:
    - echo "install licensight-scan"
    - curl -O https://licensight.s3.eu-central-1.amazonaws.com/latest/linux/licensight-scan
    - chmod +x ./licensight-scan
    - echo "repository name is $CI_PROJECT_NAME"
    - echo "push SBOM to licensight"
    - echo "show DecoratePullRequest $CI_API_V4_URL $CI_MERGE_REQUEST_IID"
    - ./licensight-scan generate -d . -a $PROJECT_NAME -e $ENV -at $SECRET_KEY -dpr true -gat $GITLAB_ACCESS_TOKEN -btb true
  rules:
    - if: '$CI_COMMIT_BRANCH'