job:
  package-manager: maven
  allowed-updates:
    - dependency-type: direct
      update-type: all
  dependencies:
    - "org.apache.kafka:kafka-clients"
    - "org.springdoc:springdoc-openapi-starter-webmvc-ui"
  security-advisories:
    - dependency-name: "org.apache.kafka:kafka-clients"
      affected-versions:
        - <3.9.0
    - dependency-name: "org.springdoc:springdoc-openapi-starter-webmvc-ui"
      affected-versions:
        - <2.8.0
    - dependency-name: "org.springframework.boot:spring-boot-devtools"
      affected-versions:
        - <3.4.6
  security-updates-only: true
  source:
    provider: github
    repo: HUNGPNdev/Demo-Swagger-App
    directory: /
    branch: dependabot-cli
credentials:
  - type: git_source
    host: github.com
    username: x-access-token
    password: $GITHUB_TOKEN
