name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-licensight-scan-without-access-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install licensight-file
        run: |
          echo "install licensight-file"
          curl -O https://licensight.s3.eu-central-1.amazonaws.com/test/licensight-scan
          chmod +x ./licensight-scan

      - name: build-licensight-scan-without-access-token
        run: |
          ./licensight-scan generate -d . -a ${{ secrets.PROJECT_NAME }} -e ${{ secrets.ENV }} -at ${{ secrets.SECRET_KEY }} -dpr -b $CI_COMMIT_REF_NAME

  build-licensight-scan-with-access-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install licensight-file
        run: |
          echo "install licensight-file"
          curl -O https://licensight.s3.eu-central-1.amazonaws.com/test/licensight-scan
          chmod +x ./licensight-scan
      - name: build-licensight-scan-without-access-token
        env:
          GITHUB_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          LICENSIGHT_APPLICATION_NAME: ${{ secrets.PROJECT_NAME }}
        run: |
          ./licensight-scan generate -d . -a ${{ vars.LICENSIGHT_APPLICATION_NAME }} -e ${{ secrets.ENV }} -at ${{ secrets.SECRET_KEY }} -dpr -b $CI_COMMIT_REF_NAME