name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-licensight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install licensight-file
        run: |
          if [ "$GITHUB_ACTIONS" == "true" ]; then
            echo "This is a GitHub Actions pipeline"
          fi
          
          echo "echo"
          echo "GITHUB_EVENT_PATH $GITHUB_EVENT_PATH"
          cat "$GITHUB_EVENT_PATH"
          echo "server_url ${{ github.api_url }}"
          echo "PR URL is ${{ github.event.pull_request.html_url }}" | echo "PR URL: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
          echo "API comment URL: https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          echo "install licensight-file"
          curl -O https://licensight.s3.eu-central-1.amazonaws.com/test/licensight-scan
          chmod +x ./licensight-scan

      - name: Push SBOM to licensight
        env:
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          ENV: ${{ secrets.ENV }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CI_API_V4_URL: ${{ secrets.CI_API_V4_URL }}
        run: |
          echo "repository name is $PROJECT_NAME ${{ secrets.ENV }}" $PROJECT_NAME $ENV $SECRET_KEY
          echo "push SBOM to licensight"
          ./licensight-scan generate -d . -a $PROJECT_NAME -e $ENV -at $SECRET_KEY -dpr true -btb true

