name: licensight-fix-vulnerabilities

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo extra values
        run: |
          echo "fixedVersion- 1.11.0"
          echo "severity- HIGH"
          echo "severityDecimalScore- 8.8"
          echo "sourceId- GHSA-wxr5-93ph-8wr9"
          echo "vulnId- 68957aeaefb50811de6eb4f0"
